#!/usr/bin/env python3
"""Generate and validate KirzKit's source-pack inventory."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def markdown_files(directory: Path) -> list[Path]:
    return sorted(p for p in directory.rglob("*.md") if p.is_file())


def canonical_agent_files() -> list[Path]:
    return sorted(
        p for p in (ROOT / "agents").glob("*.md")
        if p.is_file() and p.name not in {"README.md", "CONTRIBUTING.md", "CONTRIBUTING_zh-CN.md"}
    )


def canonical_skill_files() -> list[Path]:
    return sorted(p / "SKILL.md" for p in (ROOT / "skills").iterdir() if p.is_dir() and (p / "SKILL.md").is_file())


def inventory() -> dict[str, list[Path]]:
    agents = canonical_agent_files()
    skills = canonical_skill_files()
    workflows = sorted(p for p in (ROOT / "workflows").glob("*.md") if p.is_file())
    return {
        "agents": agents,
        "skills": skills,
        "workflows": workflows,
        "nested_agents": markdown_files(ROOT / "agents"),
        "nested_skills": sorted(p for p in (ROOT / "skills").rglob("SKILL.md") if p.is_file()),
        "nested_workflows": markdown_files(ROOT / "workflows"),
    }


def relative(paths: list[Path]) -> list[str]:
    return [p.relative_to(ROOT).as_posix() for p in paths]


def render(data: dict[str, list[Path]]) -> str:
    lines = [
        "# KirzKit Source Inventory",
        "",
        "> Generated by `python scripts/inventory.py`. Do not edit manually.",
        "",
        "## Counts",
        "",
        f"- Agents: **{len(data['agents'])}** canonical personas",
        f"- Skills: **{len(data['skills'])}** top-level installable packs",
        f"- Workflows: **{len(data['workflows'])}** top-level guides",
        f"- Nested agent definitions: **{len(data['nested_agents'])}**",
        f"- Nested skill variants: **{len(data['nested_skills'])}**",
        f"- Nested workflow guides: **{len(data['nested_workflows'])}**",
        "",
        "## Agent Categories",
        "",
        "| Category | Count |",
        "|---|---:|",
        f"| Canonical agent personas | {len(data['agents'])} |",
        f"| Nested/folder agent definitions | {len(data['nested_agents'])} |",
        f"| Top-level installable skill packs | {len(data['skills'])} |",
        f"| Nested skill variants | {len(data['nested_skills'])} |",
        f"| Top-level workflow guides | {len(data['workflows'])} |",
        f"| Nested workflow guides | {len(data['nested_workflows'])} |",
        "",
    ]
    for key, label in (("agents", "Agents"), ("skills", "Skills"), ("workflows", "Workflows")):
        lines += [f"## {label}", ""]
        lines += [f"- `{item}`" for item in relative(data[key])]
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def validate(data: dict[str, list[Path]]) -> tuple[list[str], list[str]]:
    errors: list[str] = []
    warnings: list[str] = []
    seen: dict[str, str] = {}
    for path in data["skills"]:
        text = path.read_text(encoding="utf-8", errors="replace")
        match = re.search(r"^name:\s*[\"']?([^\"'\n]+)", text, re.MULTILINE)
        if not match:
            warnings.append(f"Missing frontmatter name: {path.relative_to(ROOT)}")
            continue
        name = match.group(1).strip()
        if name in seen:
            warnings.append(f"Duplicate skill name '{name}': {seen[name]} and {path.relative_to(ROOT)}")
        seen[name] = str(path.relative_to(ROOT))
    for required in ("SKILL.md", "README.md"):
        if not (ROOT / required).exists():
            errors.append(f"Missing required repository file: {required}")
    return errors, warnings


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate generated inventory and metadata")
    args = parser.parse_args()
    data = inventory()
    output = ROOT / "INVENTORY.md"
    rendered = render(data)
    if args.check:
        errors, warnings = validate(data)
        if output.read_text(encoding="utf-8") != rendered if output.exists() else True:
            errors.append("INVENTORY.md is stale; run python scripts/inventory.py")
        for error in errors:
            print(f"ERROR: {error}")
        for warning in warnings:
            print(f"WARNING: {warning}")
        print(f"Inventory: {len(data['agents'])} agents, {len(data['skills'])} skills, {len(data['workflows'])} workflows")
        return 1 if errors else 0
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"Wrote {output.relative_to(ROOT)}")
    print(f"Inventory: {len(data['agents'])} agents, {len(data['skills'])} skills, {len(data['workflows'])} workflows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
